openapi: 3.0.0
info:
  title: Attachments API
  version: 1.0.0
paths:
  /attachments:
    post:
      summary: Create an attachment
      security:
        - jwtAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: Name of the file
                extension:
                  type: string
                  description: File extension
                file:
                  type: string
                  format: binary
                  description: Binary data of the file
              required:
                - filename
                - extension
                - file
      responses:
        '201':
          description: Attachment created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  blobUuid:
                    type: string
                    format: uuid
                  uploadDate:
                    type: string
                    format: date
        '400':
          description: Validation error
        '403':
          description: JWT authentication required

  /attachments/{blobUuid}:
    get:
      summary: Get attachment data by UUID
      security:
        - jwtAuth: []
      parameters:
        - in: path
          name: blobUuid
          required: true
          schema:
            type: string
            format: uuid
          description: UUID of the blob to retrieve
      responses:
        '200':
          description: Attachment data
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Blob UUID not found
        '403':
          description: JWT authentication required
