openapi: 3.0.0
info:
  title: User Authentication API
  version: 1.0.0  
paths:
  /signup:
    post:
      summary: User signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                username:
                  type: string
      responses:
        '200':
          description: Signup successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  tenantID:
                    type: string
        '409':
          description: Email already in use
        '400':
          description: Password complexity not met

  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '404':
          description: Email does not exist
        '401':
          description: Password does not match
        '400':
          description: Bad request due to parameter type mismatch or other validation errors

  /whoami:
    get:
      summary: User identity
      security:
        - jwtAuth: []
      responses:
        '200':
          description: User identity returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  tenantID:
                    type: string
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
