openapi: 3.0.0
info:
  title: Project Management API
  version: 1.0.0
paths:
  /Projects:
    post:
      summary: Creating a project
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/Request/ProjectRequest.yaml'
      responses:
        '201':
          description: Project created successfully
          content:
            application/json:
              schema:
                $ref: './schemas/Response/ProjectResponse.yaml'
        '400':
          description: Validation error
        '403':
          description: JWT authentication required

    get:
      summary: View all projects
      security:
        - jwtAuth: []
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/Response/ProjectResponse.yaml'
        '403':
          description: JWT authentication required

  /Projects/{projectId}:
    patch:
      summary: Updating a project
      security:
        - jwtAuth: []
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/Request/ProjectDiffRequest.yaml'
      responses:
        '200':
          description: Project updated successfully
          content:
            application/json:
              schema:
                $ref: './schemas/Response/ProjectDiffResponse.yaml'
        '400':
          description: Validation error
        '403':
          description: JWT authentication required
        '404':
          description: Project ID not found

    get:
      summary: Project Overview
      security:
        - jwtAuth: []
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Project details with history and events
          content:
            application/json:
              schema:
                type: object
                properties:
                  projectDetails:
                    $ref: './schemas/Response/ProjectResponse.yaml'
                  diffs:
                    type: array
                    items:
                      $ref: './schemas/Response/ProjectDiffResponse.yaml'
                  events:
                    type: array
                    items:
                      $ref: './schemas/Response/EventResponse.yaml'
        '404':
          description: Project ID not found
        '403':
          description: JWT authentication required

components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
     
