/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects/{projectID}/Collaborators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Viewing Current collaborators on a project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of project collaborators */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["collaborators"][];
                    };
                };
                /** @description JWT authentication required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project ID not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Adding a Collaborator to a project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectID: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        collaborator: string;
                    };
                };
            };
            responses: {
                /** @description Collaborator added to the project */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description JWT authentication required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project ID not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/Collaborators/{collaboratorTenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removing a collaborator from a project */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectID: string;
                    collaboratorTenantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collaborator removed from the project */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cannot remove collaborator, still present on projects */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description JWT authentication required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Collaborator or Project ID not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        collaborators: {
            friendlyName?: string;
            /** Format: uuid */
            tenantID?: string;
            /** @enum {string} */
            status?: "PENDING" | "ACTIVE";
            projects?: {
                projectName: string;
                /** Format: uuid */
                projectID: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
