name: Deploy to Google App Engine

on:
  push:
      branches:
          - master
jobs:
  deploy:
    environment: Dev Test
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Set default GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --quiet \
            --set-env-vars \
            JWTKey=${{ secrets.JWTKEY }},\
            MongoConnectionString=${{ secrets.MONGOCONNECTIONSTRING }}
