name: Deploy to Google App Engine

on:
  push:
      branches:
          - main
jobs:
  deploy:
    environment: Dev Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject Environment Variables into app.yaml
        run: |
          sed -i 's|JWTKEY_PLACEHOLDER|${{ secrets.JWTKEY }}|' app.yaml
          sed -i 's|MONGOCONNECTIONSTRING_PLACEHOLDER|${{ secrets.MONGOCONNECTIONSTRING }}|' app.yaml
          cat app.yaml
        
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

        
      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy 