openapi: 3.0.0
info:
  title: Project Management API
  version: 1.0.0
servers:
  - url: '${host}'
paths:
  # Previous paths remain unchanged

components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Project:
      type: object
      properties:
        projectName:
          type: string
        projectId:
          type: string
          format: uuid
        startedDate:
          type: string
          format: date
        customMetaData:
          type: object
          additionalProperties:
            type: string
    ProjectUpdate:
      type: object
      properties:
        projectName:
          type: string
        customMetaData:
          type: object
          additionalProperties:
            type: string
    ProjectHistory:
      type: object
      properties:
        projectName:
          type: string
        projectId:
          type: string
          format: uuid
        startedDate:
          type: string
          format: date
        customMetaData:
          type: object
          additionalProperties:
            type: string
        diffs:
          type: array
          items:
            $ref: '#/components/schemas/Diff'
        events:
          type: array
          items:
            type: object
            # Define the structure for events as needed
    Diff:
      type: object
      properties:
        projectName:
          type: object
          properties:
            old:
              type: string
            new:
              type: string
        customMetaData:
          type: object
          additionalProperties:
            type: object
            properties:
              old:
                type: string
              new:
                type: string

